# Lab_1.1.1

# 1.	Compute the scalar product of two n-dimensional vectors.

In [1]:
def ProductTwoVectors (v1,v2):
    sum=0
    element = 0
    for element in range(len(v1)):
        sum=sum+(v1[element]*v2[element])
    return(sum)
            
                      
    

In [4]:
v1=[1,2,3]
v2=[4,5,6]
ProductTwoVectors(v1,v2)

32

<br>Pseudocode: Define two vectors as x with n dimensions and y with n dimensions.
<br> check that the length of both vectors are the same or else return error.
<br>Iterate through all the elements for each vector: 
<br>    For element from 1 to nth dimension, pass elements for both x and y into the numpy.dot function. Print output Concrete example below.


In [1]:
import numpy as np

In [5]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.dot(x,y))

32


# 2.	Compute the cross product of two 3D vectors.

In [6]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.cross(x,y))

[-3  6 -3]


# 3.	Compute the Hademard product of two vectors.

Hadamard Product is elementwise multiplication and it outputs a vector.

In [7]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x*y)

[ 4 10 18]


# 4.	Compute the sum of two matrices.


In [13]:

m1 = np.array([[1,2,3], [4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])
print(m1+m2)

[[ 8 10 12]
 [14 16 18]]


# 5.	Compute the product of two matrices.

In [19]:
import numpy as np
m3=np.array([[13,14,15],[16,17,18]])
m4=np.array([[19,20,21],[22,23,24],[25,26,27]])
print(np.dot(m3,m4))

[[ 930  972 1014]
 [1128 1179 1230]]


# 6.	Compute the determinant of an n x n matrix.




Background Information:
Determinants for larger matrices can be recursively obtained by the Laplace Expansion. The fomula for Laplace Expansion is 
Laplace's formula expresses the determinant of a matrix in terms of its minors. The minor Mi,j is defined to be the determinant of the (n−1) × (n−1)-matrix that results from matrix A by removing the i-th row and the j-th column. 

Explanation of terms in Laplace Expansion: 
1) Summation from j=1 to n: This means the sum from j=1 to n, in this case from the first column to the last one. 
2) (−1)**1+j: This ensures that alternating entries will be added and subtracted. 
3) a1j: Refers to the element the matrix A at position 1,j. 
4) M1j: Refers to the minor of matrix A after removing row 1 and column j 
In summary, we are taking the sum from j=1 to n, of -1 to the power (1+j) times the element as at index (1,j) in the original matrix times the minor of the matrix after removing row 1 and column j. 
Pseudocode:

Suppose that we have an nxn matrix A, with number of columns j. 
If the number of columns is 2, compute the determinant using ad-bc and return the result. 
Else: Iterate through all of the columns. 
Calculate the multiplier by taking -1 to the power (1+j) times the element at A[1][j] 
Delete row 1 and column j from A, and create a new matrix X. 
Find the determinant of X through recursion (start again at the top with A=X). 
Multiply the determinant by the multiplier. 
Sum all of the values and return result.


Source: http://www.vikparuchuri.com/blog/find-the-determinant-of-a-matrix/




# 7.    Compute the inverse of an n x n matrix.

In [ ]:
Compute the inverse of an n x n matrix.
Background Information:
Why do we invert matrices? We need to invert matrices because we cannot divide matrices. Matrix "division" is actually just multiplying a matrix by its inverse, to get the identity matrix. Say we have the equation 1=YX, with Y and X being matrices. If we want to solve for X, we need to divide by Y. Instead, we will have to multiply by the inverse of Y, so that we get Y**−1=X. 
Use the Gauss-Jordan Elimination method.

Steps: 

1) To invert a matrix, start by adding an identity matrix to the right of the matrix. 
2) The basic row operations on the combined matrix are: 
We can swap any two rows. 
We can multiply any row by a number than isn’t zero. 
We can add a row times a number to another row. 
3) The goal is to get the matrix on the left in row echelon form: 
All rows with at least one nonzero element are above any rows of all zeroes. 
The first nonzero number from the left of a nonzero row is always to the right of the first nonzero number of the row above it. 
All entries in a column below a leading entry are zeroes. 
The identity matrix would be an example of a matrix in row echelon form. 
We should perform our row operations on both the left hand and right hand matrices. Once we are done converting our left hand matrix into row echelon form, our right hand matrix will be the inverse of the original matrix. 
Pseudocode:


Start with i=1, j=1, and matrix Z. 
Concatenate Z with its identity matrix, make matrix X. 
Is everything in the column j at and below X[i][j] zero? If yes, increment j and restart from the top. 
If j equals the number of columns in Z, we are done. 
k is the row index of the first non-zero column entry. 
If k!=i, swap row k and row i, so that the highest value is reduced first. 
Divide row i by X[i][j], in order to make X[i][j]=1. 
Iterate through all the non-i rows, and subtract their j-column value times the i-row from them. This will ensure that all values in column j that are not in row i will be zero. This is a requirement of row echelon form. 
If i equals the number of rows in X or j equals the number of columns in the original matrix Z (not counting the identity), we are done. 
Otherwise, increment i and j and start from the top.
This algorithm will loop through each column, and convert it to row-echelon form. At the end, the right side of the matrix X will be the solution, the inverse.


Source: http://www.vikparuchuri.com/blog/inverting-your-very-own-matrix/
